package com.songyang;


import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.DateFormat;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

import java.math.BigDecimal;
import java.util.Date;

@Document(indexName = "book" ,shards = 1,replicas = 0,useServerConfiguration = true,createIndex = false)
public class EsBook {
    @Id
    private int id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_delete
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Boolean ,name = "is_delete" )
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.conut
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Long)
    private int count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word")
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.borrow_conut
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Long)
    private int borrowCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_time
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Date,name = "publish_time",format = DateFormat.date_optional_time)
    @JsonFormat(timezone = "GMT+8")
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Date,name = "create_time",format = DateFormat.date_optional_time)
    @JsonFormat(timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Date,name="update_time" ,format = DateFormat.date_optional_time)
    @JsonFormat(timezone = "GMT+8")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.overdue_price
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Long,name = "overdue_price")

    private BigDecimal overduePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_main_name
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word" ,name = "pic_main_name")
    private String picMainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_host
     *
     * @mbggenerated
     */
    @Field(type = FieldType.Text, analyzer = "ik_max_word",name = "pic_host")
    private String picHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated
     */
    public EsBook(int id, String name, Boolean isDelete, int count, String author, int borrowCount, String title, Date publishTime, Date createTime, Date updateTime, BigDecimal overduePrice, String picMainName, String picHost) {
        this.id = id;
        this.name = name;
        this.isDelete = isDelete;
        this.count = count;
        this.author = author;
        this.borrowCount = borrowCount;
        this.title = title;
        this.publishTime = publishTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.overduePrice = overduePrice;
        this.picMainName = picMainName;
        this.picHost = picHost;
    }
    public  EsBook(){

    }

    public int getId() {
        return id;
    }
    public interface Type{
         String TITLE ="title";
         String AUTHOR="author";
         String NAME= "name";


    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public int getBorrowCount() {
        return borrowCount;
    }

    public void setBorrowCount(int borrowCount) {
        this.borrowCount = borrowCount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public BigDecimal getOverduePrice() {
        return overduePrice;
    }

    public void setOverduePrice(BigDecimal overduePrice) {
        this.overduePrice = overduePrice;
    }

    public String getPicMainName() {
        return picMainName;
    }

    public void setPicMainName(String picMainName) {
        this.picMainName = picMainName;
    }

    public String getPicHost() {
        return picHost;
    }

    public void setPicHost(String picHost) {
        this.picHost = picHost;
    }
}