server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.223.129:3306/mysql_study?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.springmb.dao

#showSql
logging:
  level:
    com:
      example:
        mapper : debug