package com.songyang.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Book implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.conut
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.borrow_conut
     *
     * @mbggenerated
     */
    private Integer borrowCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.overdue_price
     *
     * @mbggenerated
     */
    private BigDecimal overduePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_main_name
     *
     * @mbggenerated
     */
    private String picMainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_host
     *
     * @mbggenerated
     */
    private String picHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;



    private  int categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.is_delete
     *
     * @return the value of book.is_delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.is_delete
     *
     * @param isDelete the value for book.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.conut
     *
     * @return the value of book.conut
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.conut
     *
     * @param count the value for book.conut
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.borrow_conut
     *
     * @return the value of book.borrow_conut
     *
     * @mbggenerated
     */
    public Integer getBorrowCount() {
        return borrowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.borrow_conut
     *
     * @param borrowCount the value for book.borrow_conut
     *
     * @mbggenerated
     */
    public void setBorrowCount(Integer borrowCount) {
        this.borrowCount = borrowCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_time
     *
     * @return the value of book.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish_time
     *
     * @param publishTime the value for book.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.create_time
     *
     * @return the value of book.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.create_time
     *
     * @param createTime the value for book.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.update_time
     *
     * @return the value of book.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.update_time
     *
     * @param updateTime the value for book.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.overdue_price
     *
     * @return the value of book.overdue_price
     *
     * @mbggenerated
     */
    public BigDecimal getOverduePrice() {
        return overduePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.overdue_price
     *
     * @param overduePrice the value for book.overdue_price
     *
     * @mbggenerated
     */
    public void setOverduePrice(BigDecimal overduePrice) {
        this.overduePrice = overduePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pic_main_name
     *
     * @return the value of book.pic_main_name
     *
     * @mbggenerated
     */
    public String getPicMainName() {
        return picMainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pic_main_name
     *
     * @param picMainName the value for book.pic_main_name
     *
     * @mbggenerated
     */
    public void setPicMainName(String picMainName) {
        this.picMainName = picMainName == null ? null : picMainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pic_host
     *
     * @return the value of book.pic_host
     *
     * @mbggenerated
     */
    public String getPicHost() {
        return picHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pic_host
     *
     * @param picHost the value for book.pic_host
     *
     * @mbggenerated
     */
    public void setPicHost(String picHost) {
        this.picHost = picHost == null ? null : picHost.trim();
    }

    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", conut=").append(count);
        sb.append(", author=").append(author);
        sb.append(", borrowConut=").append(borrowCount);
        sb.append(", title=").append(title);
        sb.append(", publishTime=").append(publishTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", overduePrice=").append(overduePrice);
        sb.append(", picMainName=").append(picMainName);
        sb.append(", picHost=").append(picHost);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}