package com.songyang.pojo;

import java.io.Serializable;

public class UserPic implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.pic_name
     *
     * @mbggenerated
     */
    private String picName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.pic_host
     *
     * @mbggenerated
     */
    private String picHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pic.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.id
     *
     * @return the value of user_pic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.id
     *
     * @param id the value for user_pic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.pic_name
     *
     * @return the value of user_pic.pic_name
     *
     * @mbggenerated
     */
    public String getPicName() {
        return picName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.pic_name
     *
     * @param picName the value for user_pic.pic_name
     *
     * @mbggenerated
     */
    public void setPicName(String picName) {
        this.picName = picName == null ? null : picName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.pic_host
     *
     * @return the value of user_pic.pic_host
     *
     * @mbggenerated
     */
    public String getPicHost() {
        return picHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.pic_host
     *
     * @param picHost the value for user_pic.pic_host
     *
     * @mbggenerated
     */
    public void setPicHost(String picHost) {
        this.picHost = picHost == null ? null : picHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pic.user_id
     *
     * @return the value of user_pic.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pic.user_id
     *
     * @param userId the value for user_pic.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", picName=").append(picName);
        sb.append(", picHost=").append(picHost);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}