package com.songyang.vo;



import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class BookVo {
    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.is_delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.conut
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.borrow_conut
     *
     * @mbggenerated
     */
    private Integer borrowCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.create_time
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.update_time
     *
     * @mbggenerated
     */


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.overdue_price
     *
     * @mbggenerated
     */
    private BigDecimal overduePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_main_name
     *
     * @mbggenerated
     */
    private String picMainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pic_host
     *
     * @mbggenerated
     */
    private String picHost;


    private List<CategoryVo> categoryVos;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getBorrowCount() {
        return borrowCount;
    }

    public void setBorrowCount(Integer borrowCount) {
        this.borrowCount = borrowCount;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getPublishTime() {
        return publishTime;
    }

    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    public BigDecimal getOverduePrice() {
        return overduePrice;
    }

    public void setOverduePrice(BigDecimal overduePrice) {
        this.overduePrice = overduePrice;
    }

    public String getPicMainName() {
        return picMainName;
    }

    public void setPicMainName(String picMainName) {
        this.picMainName = picMainName;
    }

    public String getPicHost() {
        return picHost;
    }

    public void setPicHost(String picHost) {
        this.picHost = picHost;
    }

    public List<CategoryVo> getCategoryVos() {
        return categoryVos;
    }

    public void setCategoryVos(List<CategoryVo> categoryVos) {
        this.categoryVos = categoryVos;
    }
}
