package com.songyang.dao;

import com.songyang.pojo.BookPic;

public interface BookPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    int insert(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    int insertSelective(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    BookPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BookPic record);
}