package com.songyang.dao;

import com.songyang.pojo.Category;

import java.util.List;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    int insertSelective(Category record);


    int deleteByPrimary(Integer[] ids);

    int updateByPrimary(Category category);

    List selectCategorys();

    int selectCategoryIdByname(String name);
}